force-app/main/default/objects/Location/fields/Avg_FootFall__c.field-meta.xml
<CustomField>
    <fullName>Avg_FootFall__c</fullName>
    <label>Avg FootFall</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location/fields/Avg_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Avg_Revenue__c</fullName>
    <label>Avg Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location/fields/Demand_Score__c.field-meta.xml
<CustomField>
    <fullName>Demand_Score__c</fullName>
    <label>Demand Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StoreLocationAnalysis.cls
public class StoreLocationAnalysis {
    
    public class RequestWrapper {
        @InvocableVariable(label='Store Location'
                          description='Contains the location where the user wants to open a new retail Store')
        public string newLocationSec;
    }
    
    public class ResponseWrapper {
        @InvocableVariable(label='Store Analysis'
                          description='Contains the store analysis done for the asked location')
        public string finalStoreAnalysis;
        
    }
    
    @InvocableMethod(label='Analyze Store Expansion Location')
    public static List<ResponseWrapper> analyzeLocation(List<RequestWrapper> requests) {
        List<ResponseWrapper> responses = new List<ResponseWrapper>();
        
        for(RequestWrapper req: requests) {
            
            List<Schema.Location> loc = [SELECT Name, Location,Demand_Score__c,Avg_FootFall__c,Competition_Level__c,Avg_Revenue__c FROM Location
                           WHERE Name=: req.newLocationSec LIMIT 1];
        }
        
        String Recommendation='';
        
        return responses;
    }

}